apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-helm-demo
  namespace: docker-k8s-helm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
          - name: app
            image: {{ .Values.image.name }}:{{ .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080
            env:
              - name: mongo.host
                value: mongo-cluster-ip-service
              - name: mongo.pass
                valueFrom:
                  secretKeyRef:
                    name: mongo-pass
                    key: mongoPass
