apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # can be used by a single node... ReadOnlyMany (multiple nodes can read). RearWriteMany (multiple nodes can read/write)
  resources:
    requests:
      storage: 1Gi