apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-ip-service
  namespace: docker-k8s-helm-demo
spec:
  type: ClusterIP
  selector:
    component: mongo
  ports:
    - port: 27017
      targetPort: 27017